# Generated by Django 4.1.6 on 2023-02-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
    ]
